/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frankards;

/**
 *
 * @author ZanFa595
 */
public class mainFrame extends javax.swing.JFrame {
    private Frankards frankards = new Frankards();
    private int panelWidth;
    private int panelHeight;
    private boolean showingDefinition = false;
    private int currentIndex = 0;
    private int correctCount = 0;
    private int wrongCount = 0;
    private java.awt.Color[] itemColors = new java.awt.Color[0];
    private javax.swing.JLabel wrongCountLabel = new javax.swing.JLabel("Wrong: 0");
    private javax.swing.JLabel correctCountLabel = new javax.swing.JLabel("Correct: 0");

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        panelWidth = flashcardPanel.getWidth();
        panelHeight = flashcardPanel.getHeight();

        wrongCountLabel.setForeground(java.awt.Color.RED);
        correctCountLabel.setForeground(new java.awt.Color(0, 150, 0));
        javax.swing.JPanel glass = new javax.swing.JPanel(null) {
            @Override
            public boolean contains(int x, int y) {
                for (java.awt.Component c : getComponents()) {
                    if (c.getBounds().contains(x, y)) return true;
                }
                return false;
            }
        };
        glass.setOpaque(false);
        glass.add(wrongCountLabel);
        glass.add(correctCountLabel);
        setGlassPane(glass);
        glass.setVisible(true);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                java.awt.Point p1 = javax.swing.SwingUtilities.convertPoint(
                    jScrollPane1, 0, jScrollPane1.getHeight() + 4, getRootPane());
                wrongCountLabel.setBounds(p1.x, p1.y, 80, 18);
                java.awt.Point p2 = javax.swing.SwingUtilities.convertPoint(
                    jScrollPane2, 0, jScrollPane2.getHeight() + 4, getRootPane());
                correctCountLabel.setBounds(p2.x, p2.y, 80, 18);
            }
        });

        termsList.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (index < itemColors.length && itemColors[index] != null) {
                    c.setForeground(itemColors[index]);
                }
                return c;
            }
        });
        definitionsList.setCellRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (index < itemColors.length && itemColors[index] != null) {
                    c.setForeground(itemColors[index]);
                }
                return c;
            }
        });

        turnerSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                turnerSliderStateChanged();
            }
        });

        wrongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAndAdvance(java.awt.Color.RED, false);
            }
        });
        correctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAndAdvance(new java.awt.Color(0, 150, 0), true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        termTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        definitionTextField = new javax.swing.JTextField();
        enterTermButton = new javax.swing.JButton();
        flashcardPanel = new javax.swing.JPanel();
        flashcardLabel = new javax.swing.JLabel();
        turnerSlider = new javax.swing.JSlider();
        correctButton = new javax.swing.JButton();
        wrongButton = new javax.swing.JButton();
        listProgress = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        termsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        definitionsList = new javax.swing.JList<>();
        startButton = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        termTextField.setText("term");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("FranKards");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel2.setText("enter a flashcard");

        definitionTextField.setText("definition");

        enterTermButton.setText("enter");
        enterTermButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTermButtonActionPerformed(evt);
            }
        });

        flashcardPanel.setBackground(new java.awt.Color(153, 153, 255));

        flashcardLabel.setText("jLabel4");

        javax.swing.GroupLayout flashcardPanelLayout = new javax.swing.GroupLayout(flashcardPanel);
        flashcardPanel.setLayout(flashcardPanelLayout);
        flashcardPanelLayout.setHorizontalGroup(
            flashcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flashcardPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(flashcardLabel)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        flashcardPanelLayout.setVerticalGroup(
            flashcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flashcardPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(flashcardLabel)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        turnerSlider.setValue(0);

        correctButton.setBackground(new java.awt.Color(0, 204, 51));
        correctButton.setText("correct");

        wrongButton.setBackground(new java.awt.Color(255, 102, 102));
        wrongButton.setText("Wrong");

        jScrollPane1.setViewportView(termsList);

        jScrollPane2.setViewportView(definitionsList);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(flashcardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(wrongButton)
                                .addGap(103, 103, 103)
                                .addComponent(correctButton)))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(listProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(termTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(definitionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(enterTermButton))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(turnerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(startButton)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(definitionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterTermButton))
                .addGap(22, 22, 22)
                .addComponent(listProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2))
                    .addComponent(flashcardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(turnerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongButton)
                    .addComponent(correctButton))
                .addGap(29, 29, 29)
                .addComponent(startButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterTermButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTermButtonActionPerformed
        String term = termTextField.getText();
        String definition = definitionTextField.getText();
        
        frankards.enterList(term, definition);
        termsList.setListData(frankards.getTerms().toArray(new String[0]));
        definitionsList.setListData(frankards.getDefinitions().toArray(new String[0]));

        java.awt.Color[] newColors = new java.awt.Color[frankards.getTerms().size()];
        for (int i = 0; i < Math.min(itemColors.length, newColors.length); i++) {
            newColors[i] = itemColors[i];
        }
        itemColors = newColors;

        listProgress.setMaximum(frankards.getTerms().size());
        listProgress.setValue(currentIndex);
    }//GEN-LAST:event_enterTermButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (!frankards.getTerms().isEmpty()) {
            currentIndex = 0;
            correctCount = 0;
            wrongCount = 0;
            itemColors = new java.awt.Color[frankards.getTerms().size()];
            for (int i = 0; i < itemColors.length; i++) {
                itemColors[i] = null;
            }
            wrongCountLabel.setText("Wrong: 0");
            correctCountLabel.setText("Correct: 0");
            showingDefinition = false;
            turnerSlider.setValue(0);
            listProgress.setMaximum(frankards.getTerms().size());
            listProgress.setValue(0);
            termsList.repaint();
            definitionsList.repaint();
            flashcardLabel.setText(frankards.getTerms().get(0));
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void markAndAdvance(java.awt.Color color, boolean isCorrect) {
        if (frankards.getTerms().isEmpty() || currentIndex >= frankards.getTerms().size()) return;

        itemColors[currentIndex] = color;
        termsList.repaint();
        definitionsList.repaint();

        if (isCorrect) {
            correctCount++;
            correctCountLabel.setText("Correct: " + correctCount);
        } else {
            wrongCount++;
            wrongCountLabel.setText("Wrong: " + wrongCount);
        }

        currentIndex++;
        showingDefinition = false;
        turnerSlider.setValue(0);
        listProgress.setValue(currentIndex);

        if (currentIndex < frankards.getTerms().size()) {
            flashcardLabel.setText(frankards.getTerms().get(currentIndex));
        } else {
            flashcardLabel.setText("Done!");
        }
    }

    private void turnerSliderStateChanged() {
        int value = turnerSlider.getValue();

        if (value >= 50 && !showingDefinition) {
            showingDefinition = true;
            if (!frankards.getDefinitions().isEmpty() && currentIndex < frankards.getDefinitions().size()) {
                flashcardLabel.setText(frankards.getDefinitions().get(currentIndex));
            }
        } else if (value < 50 && showingDefinition) {
            showingDefinition = false;
            if (!frankards.getTerms().isEmpty() && currentIndex < frankards.getTerms().size()) {
                flashcardLabel.setText(frankards.getTerms().get(currentIndex));
            }
        }

        double scale = Math.abs(value - 50) / 50.0;
        int newWidth = Math.max(1, (int) (panelWidth * scale));
        int newHeight = Math.max(1, (int) (panelHeight * scale));
        flashcardPanel.setPreferredSize(new java.awt.Dimension(newWidth, newHeight));
        getContentPane().revalidate();
        repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton correctButton;
    private javax.swing.JTextField definitionTextField;
    private javax.swing.JList<String> definitionsList;
    private javax.swing.JButton enterTermButton;
    private javax.swing.JLabel flashcardLabel;
    private javax.swing.JPanel flashcardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar listProgress;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField termTextField;
    private javax.swing.JList<String> termsList;
    private javax.swing.JSlider turnerSlider;
    private javax.swing.JButton wrongButton;
    // End of variables declaration//GEN-END:variables
}
