/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frankards;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Main GUI window for the FranKards flashcard application.
 * Handles flashcard entry, sequential review via an animated flip panel,
 * correct/wrong tracking with color-coded list feedback, and a progress bar
 * that updates as the user advances through the deck.
 *
 * @author ZanFa595
 */
public class mainFrame extends JFrame {
    private static final Color CORRECT_COLOR = new Color(0, 150, 0);

    private Frankards frankards = new Frankards();
    private int panelWidth;
    private int panelHeight;
    private boolean showingDefinition = false;
    private int currentIndex = 0;
    private int correctCount = 0;
    private int wrongCount = 0;
    private Color[] itemColors = new Color[0];

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        panelWidth = flashcardPanel.getWidth();
        panelHeight = flashcardPanel.getHeight();

        DefaultListCellRenderer colorRenderer = createColorRenderer();
        termsList.setCellRenderer(colorRenderer);
        definitionsList.setCellRenderer(colorRenderer);
    }

    //pris d'internet pour changer la couleur d'une seule cellule de la JList
    private DefaultListCellRenderer createColorRenderer() {
        return new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (index < itemColors.length && itemColors[index] != null) {
                    c.setForeground(itemColors[index]);
                }
                return c;
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        termTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        definitionTextField = new javax.swing.JTextField();
        enterTermButton = new javax.swing.JButton();
        flashcardPanel = new javax.swing.JPanel();
        flashcardLabel = new javax.swing.JLabel();
        turnerSlider = new javax.swing.JSlider();
        correctButton = new javax.swing.JButton();
        wrongButton = new javax.swing.JButton();
        listProgress = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        termsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        definitionsList = new javax.swing.JList<>();
        startButton = new javax.swing.JButton();
        wrong = new javax.swing.JLabel();
        correct = new javax.swing.JLabel();
        wrongCountLabel = new javax.swing.JLabel();
        correctCountLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        termTextField.setText("term");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("FranKards");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel2.setText("enter a flashcard");

        definitionTextField.setText("definition");

        enterTermButton.setText("enter");
        enterTermButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTermButtonActionPerformed(evt);
            }
        });

        flashcardPanel.setBackground(new java.awt.Color(153, 153, 255));

        flashcardLabel.setText("jLabel4");

        javax.swing.GroupLayout flashcardPanelLayout = new javax.swing.GroupLayout(flashcardPanel);
        flashcardPanel.setLayout(flashcardPanelLayout);
        flashcardPanelLayout.setHorizontalGroup(
            flashcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flashcardPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(flashcardLabel)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        flashcardPanelLayout.setVerticalGroup(
            flashcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flashcardPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(flashcardLabel)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        turnerSlider.setValue(0);
        turnerSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                turnerSliderStateChanged(evt);
            }
        });

        correctButton.setBackground(new java.awt.Color(0, 204, 51));
        correctButton.setText("correct");
        correctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctButtonActionPerformed(evt);
            }
        });

        wrongButton.setBackground(new java.awt.Color(255, 102, 102));
        wrongButton.setText("Wrong");
        wrongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(termsList);

        jScrollPane2.setViewportView(definitionsList);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        wrong.setForeground(new java.awt.Color(255, 0, 0));
        wrong.setText("Wrong:");

        correct.setForeground(new java.awt.Color(0, 150, 0));
        correct.setText("Correct: ");

        wrongCountLabel.setText("jLabel4");

        correctCountLabel.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(flashcardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wrong)
                                        .addGap(18, 18, 18)
                                        .addComponent(wrongCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(wrongButton)
                                .addGap(103, 103, 103)
                                .addComponent(correctButton)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(correct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(correctCountLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(turnerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(startButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(termTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(definitionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(enterTermButton))
                                .addComponent(listProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(definitionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterTermButton))
                .addGap(22, 22, 22)
                .addComponent(listProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(wrong)
                                .addComponent(wrongCountLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(correct)
                                .addComponent(correctCountLabel))))
                    .addComponent(flashcardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(turnerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongButton)
                    .addComponent(correctButton))
                .addGap(29, 29, 29)
                .addComponent(startButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterTermButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String term = termTextField.getText();
        String definition = definitionTextField.getText();
        
        frankards.enterList(term, definition);
        termsList.setListData(frankards.getTerms().toArray(new String[0]));
        definitionsList.setListData(frankards.getDefinitions().toArray(new String[0]));

        Color[] newColors = new Color[frankards.getTermsCount()];
        for (int i = 0; i < Math.min(itemColors.length, newColors.length); i++) {
            newColors[i] = itemColors[i];
        }
        itemColors = newColors;

        //progress bar
        listProgress.setMaximum(frankards.getTermsCount());
        listProgress.setValue(currentIndex);
    }

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (!frankards.getTerms().isEmpty()) {
            currentIndex = 0;
            correctCount = 0;
            wrongCount = 0;
            itemColors = new Color[frankards.getTermsCount()];
            for (int i = 0; i < itemColors.length; i++) {
                itemColors[i] = null;
            }
            wrong.setText("Wrong: 0");
            correct.setText("Correct: 0");
            showingDefinition = false;
            turnerSlider.setValue(0);
            listProgress.setMaximum(frankards.getTerms().size());
            listProgress.setValue(0);
            termsList.repaint();
            definitionsList.repaint();
            flashcardLabel.setText(frankards.getTerms().get(0));
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void wrongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrongButtonActionPerformed
        markAndAdvance(Color.RED, false);
    }//GEN-LAST:event_wrongButtonActionPerformed

    private void correctButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctButtonActionPerformed
        markAndAdvance(Color.GREEN, true);
    }//GEN-LAST:event_correctButtonActionPerformed

    private void turnerSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_turnerSliderStateChanged
        int value = turnerSlider.getValue();

        if (value >= 50 && !showingDefinition) {
            showingDefinition = true;
            if (!frankards.getDefinitions().isEmpty() && currentIndex < frankards.getDefinitions().size()) {
                flashcardLabel.setText(frankards.getDefinitions().get(currentIndex));
            }
        } else if (value < 50 && showingDefinition) {
            showingDefinition = false;
            if (!frankards.getTerms().isEmpty() && currentIndex < frankards.getTerms().size()) {
                flashcardLabel.setText(frankards.getTerms().get(currentIndex));
            }
        }

        //code pris en partie d'internet pour faire une animation de flip du flashcard
        double scale = Math.abs(value - 50) / 50.0;
        int newWidth = Math.max(1, (int) (panelWidth * scale));
        int newHeight = Math.max(1, (int) (panelHeight * scale));
        flashcardPanel.setPreferredSize(new Dimension(newWidth, newHeight));
        getContentPane().revalidate();
        repaint();
    }//GEN-LAST:event_turnerSliderStateChanged

    private void markAndAdvance(Color color, boolean isCorrect) {
        //early return - sert a arreter l'execution d'une methode au cas ou une condition est vraie - fonctionne que pour methodes void
        if (frankards.getTerms().isEmpty() || currentIndex >= frankards.getTermsCount()) 
            return;

        itemColors[currentIndex] = color;
        termsList.repaint();
        definitionsList.repaint();

        if (isCorrect) {
            correctCount++;
            correctCountLabel.setText(String.valueOf(correctCount));
        } else {
            wrongCount++;
            wrongCountLabel.setText(String.valueOf(wrongCount));
        }

        currentIndex++;
        showingDefinition = false;
        turnerSlider.setValue(0);
        listProgress.setValue(currentIndex);

        if (currentIndex < frankards.getTermsCount()) {
            flashcardLabel.setText(frankards.getTerms().get(currentIndex));
        } else {
            flashcardLabel.setText("Done!");
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correct;
    private javax.swing.JButton correctButton;
    private javax.swing.JLabel correctCountLabel;
    private javax.swing.JTextField definitionTextField;
    private javax.swing.JList<String> definitionsList;
    private javax.swing.JButton enterTermButton;
    private javax.swing.JLabel flashcardLabel;
    private javax.swing.JPanel flashcardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar listProgress;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField termTextField;
    private javax.swing.JList<String> termsList;
    private javax.swing.JSlider turnerSlider;
    private javax.swing.JLabel wrong;
    private javax.swing.JButton wrongButton;
    private javax.swing.JLabel wrongCountLabel;
    // End of variables declaration//GEN-END:variables
}
